### POST LOGIN DATA
POST http://localhost:8080/login
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "admin@123"
}

### POST redis
GET http://localhost:8080/parent
Accept: application/json
Content-Type: application/json

